package TelaRelatorios;

import ClassesCadastro.ConexaoRelatorio;
import java.io.File;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;


public class TelaRelCliEPet extends javax.swing.JFrame {
   
    public TelaRelCliEPet() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotaoRelatorio = new javax.swing.JButton();
        BotaoSalvarPdf = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        BotaoRelatorio.setText("Gerar Relatorio");
        BotaoRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoRelatorioActionPerformed(evt);
            }
        });

        BotaoSalvarPdf.setText("Salvar em PDF");
        BotaoSalvarPdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoSalvarPdfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotaoSalvarPdf)
                    .addComponent(BotaoRelatorio))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(156, Short.MAX_VALUE)
                .addComponent(BotaoRelatorio)
                .addGap(18, 18, 18)
                .addComponent(BotaoSalvarPdf)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoRelatorioActionPerformed
            
        ConexaoRelatorio relatorio = new ConexaoRelatorio();
        relatorio.carregarRelatorio("Relatorios/Clientesepets.jrxml", null);
    }//GEN-LAST:event_BotaoRelatorioActionPerformed

    private void BotaoSalvarPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoSalvarPdfActionPerformed
        ConexaoRelatorio relatorio = new ConexaoRelatorio();
        String caminhoRelatorio = "Relatorios/Clientesepets.jrxml";
        
        // Abre um JFileChooser para selecionar onde salvar o arquivo PDF
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Salvar Relatório em PDF");
        
        // Define a opção de salvar arquivo
        int userSelection = fileChooser.showSaveDialog(this);
        
        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToSave = fileChooser.getSelectedFile();
            String caminhoDestino = fileToSave.getAbsolutePath();
            
            // Se o caminho não terminar com .pdf, adiciona a extensão
            if (!caminhoDestino.toLowerCase().endsWith(".pdf")) {
                caminhoDestino += ".pdf";
            }
        
        // Pode adicionar parâmetros se necessário, aqui estamos passando null
        Map<String, Object> parametros = new HashMap<>();
        
        relatorio.salvarRelatorioPdf(caminhoRelatorio, parametros, caminhoDestino);
        JOptionPane.showMessageDialog(this, "Relatório salvo em PDF com sucesso!");    
        }
    }//GEN-LAST:event_BotaoSalvarPdfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaRelCliEPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaRelCliEPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaRelCliEPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaRelCliEPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaRelCliEPet().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoRelatorio;
    private javax.swing.JButton BotaoSalvarPdf;
    // End of variables declaration//GEN-END:variables
}
